version: '3.7'
services:
  postgres:
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: aliensoo
    image: postgis/postgis:12-3.4
    restart: always
    ports:
      - "5429:5432"
