stargazer:
  outputs:

    local:
      type: postgres
      threads: 1
      host: "{{ env_var('PG_HOST') }}"
      port: "{{ env_var('PG_PORT') | as_number }}"
      user: "{{ env_var('PG_USERNAME') }}"
      pass: "{{ env_var('PGPASSWORD') }}"
      dbname: "{{ env_var('PG_DBNAME') }}"
      schema: stargazer

  target: local